// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamHello.proto

package com.example.grpc.demo.streamHello;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:streamHello.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
