// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamHello.proto

package com.example.grpc.demo.streamHello;

public final class StreamHello {
  private StreamHello() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_streamHello_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_streamHello_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_streamHello_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_streamHello_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021StreamHello.proto\022\013streamHello\"\035\n\rStre" +
      "amRequest\022\014\n\004name\030\001 \001(\t\"\036\n\016StreamRespons" +
      "e\022\014\n\004data\030\001 \001(\t2\373\001\n\017MyStreamService\022M\n\016r" +
      "esponseStream\022\032.streamHello.StreamReques" +
      "t\032\033.streamHello.StreamResponse\"\0000\001\022L\n\rre" +
      "questStream\022\032.streamHello.StreamRequest\032" +
      "\033.streamHello.StreamResponse\"\000(\001\022K\n\nboth" +
      "Stream\022\032.streamHello.StreamRequest\032\033.str" +
      "eamHello.StreamResponse\"\000(\0010\001B2\n!com.exa" +
      "mple.grpc.demo.streamHelloB\013StreamHelloP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_streamHello_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_streamHello_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_streamHello_StreamRequest_descriptor,
        new String[] { "Name", });
    internal_static_streamHello_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_streamHello_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_streamHello_StreamResponse_descriptor,
        new String[] { "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
