// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamHello.proto

package com.example.grpc.demo.streamHello;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:streamHello.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string data = 1;</code>
   * @return The data.
   */
  String getData();
  /**
   * <code>string data = 1;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
